name: sample_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
